site_name: Mof Documentation
site_url: https://docs.mofcloud.com
repo_name: mofcloud/docs
repo_url: https://github.com/mofcloud/docs

theme:
  name: material
  language: en
  features:
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - content.code.copy

plugins:
  - glightbox
  - search
  - i18n:
      default_language: c
      languages:
        - locale: en
          name: English
          build: true
          default: true
        - locale: zh
          name: 简体中文
          build: true
          nav_translations:
            Introduction: 产品介绍
            Getting started: 快速开始
            User guide: 用户指南
            Cloud Wiki: 云百科
            FinOps Wiki: FinOps 百科
            Best practice: 最佳实践
            Contact: 联系我们
            Providers: 云厂商
            AWS: AWS
            Azure: Azure
            Google Cloud: GCP
            Alibaba: 阿里云
            Huawei: 华为云
            Tencent: 腾讯云
            UCloud: UCloud
            Baidu: 百度云
            Cloudflare: Cloudflare
            Baishan: 白山云
            Agora: 声网
            Volcengine: 火山引擎
            NetEaseYidun: 网易易盾
            NetEaseYunxin: 网易云信
            ECloudValley(enterprise): ECloudValley(私有版)
            MeshCloud(enterprise): 脉时云(私有版)
            CustomCloud: 自定义云
            Smart bill: 智能账单
            Server analysis: 服务器分析
            Smart monthly bill: 智能月账单
            Monthly bill: 月账单
            Bill history: 历史账单
            Download bill: 下载账单
            Organization: 组织架构
            Sync: 数据同步
            Exchange Rate: 汇率中心
            User: 用户设置

markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - "Introduction": "index.md"
  - "Getting started": "getting-started/index.md"
  - "User guide":
      - "Smart bill":
          - "Smart monthly bill": "user-guide/bills/smart.md"
          - "Bill history": "user-guide/bills/history.md"
          - "Download bill": "user-guide/bills/download.md"
          - "Server analysis": "user-guide/bills/server.md"
      - "Organization": "user-guide/org/index.md"
      - "Sync": "user-guide/sync/index.md"
      - "Exchange Rate": "user-guide/exchange/index.md"
      - "User": "user-guide/user/index.md"
      - "Providers":
          - "AWS": "user-guide/providers/aws.md"
          - "Azure": "user-guide/providers/azure.md"
          - "GCP": "user-guide/providers/gcp.md"
          - "Alibaba": "user-guide/providers/alibaba.md"
          - "Huawei": "user-guide/providers/huawei.md"
          - "Tencent": "user-guide/providers/tencent.md"
          - "Volcengine": "user-guide/providers/volcengine.md"
          - "UCloud": "user-guide/providers/ucloud.md"
          - "Baidu": "user-guide/providers/baidu.md"
          - "Cloudflare": "user-guide/providers/cloudflare.md"
          - "Baishan": "user-guide/providers/baishan.md"
          - "Agora": "user-guide/providers/agora.md"
          - "NetEaseYidun": "user-guide/providers/yidun.md"
          - "NetEaseYunxin": "user-guide/providers/yunxin.md"
          - "Customs": "user-guide/providers/custom.md"
  - "Cloud Wiki": "cloud-wiki/index.md"
  - "FinOps Wiki": "finops-wiki/index.md"
  - "Best practice": "best-practice/index.md"
  - "Contact": "contact/index.md"

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2024 mofcloud
