site_name: Mof Documentation
site_url: https://mofcloud.com/docs
repo_name: mofcloud/docs-en
repo_url: https://github.com/mofcloud/docs-en

theme:
  name: material
  language: en
  logo: assets/logo.svg
  favicon: assets/favicon.svg
  features:
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - "Introduction": "index.md"
  - "Getting start":
      - "Add Cloud Account": "getting-started/index.md"
      - "Smart Bills":
          - "Features": "getting-started/smb/overview.md"
          - "Cloud Account": "getting-started/smb/abill.md"
          - "Multi Cloud": "getting-started/smb/pbill.md"
          - "Combined": "getting-started/smb/ubill.md"
      - "Data Sync": "getting-started/sync.md"
      - "Exchange": "getting-started/exchange.md"
      - "Tag Management": "getting-started/tagging.md"
      - "Settings": "getting-started/user-setting.md"
      - "Cloud Providers":
          - "Add/Update basic info": "getting-started/providers/basic.md"
          - "AWS": "getting-started/providers/aws.md"
          - "Azure": "getting-started/providers/azure.md"
          - "GCP": "getting-started/providers/gcp.md"
          - "Oracle": "getting-started/providers/oci.md"
          - "Cloudflare": "getting-started/providers/cloudflare.md"
          - "Manual": "getting-started/providers/manual.md"
          - "Alibaba Cloud": "getting-started/providers/alibaba.md"
          - "Tencent Cloud": "getting-started/providers/tencent.md"
          - "Huawei Cloud": "getting-started/providers/huawei.md"
          - "Volcengine": "getting-started/providers/volcengine.md"
          - "Baidu Cloud": "getting-started/providers/baidu.md"
          - "UCloud": "getting-started/providers/ucloud.md"
          - "Agora": "getting-started/providers/agora.md"
          - "Baishan Cloud": "getting-started/providers/baishan.md"
          - "Netease Yunxin": "getting-started/providers/yunxin.md"
      - "Communication":
          - "Wechat work": "getting-started/comm/wechat.md"
          - "DingDing": "getting-started/comm/ding.md"
          - "Lark Suit": "getting-started/comm/feishu.md"
  - "Deployment": "deployment/index.md"

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2025 mofcloud
